services:
  traefik:
    image: traefik:v3.1
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.docker/traefik/acme.json:/letsencrypt/acme.json
    networks:
      - proxy

  web:
    # jangan expose langsung ke host, Traefik yang handle
    ports: []
    expose:
      - "8000"
    networks:
      - lara-prod
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      # HTTPS router
      - traefik.http.routers.app-secure.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.app-secure.entrypoints=websecure
      - traefik.http.routers.app-secure.tls.certresolver=le
      - traefik.http.services.app.loadbalancer.server.port=8000

      # HTTP -> HTTPS redirect
      - traefik.http.routers.app.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.app.entrypoints=web
      - traefik.http.routers.app.middlewares=redirect-to-https
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https

networks:
  proxy:
    external: true